### ISSUE TITLE
typeOf(NaN)

### ISSUE THREAD

**Issue by jcubic** [garethslinn/helprjs#1]
It returns "number". is it intentional?

**Comment by garethslinn** [comment]
NaN just means the specific value cannot be represented within the limitations of the numeric type (although that could be said for all numbers that have to be rounded to fit, but NaN is a special case). A specific NaN is not considered equal to another NaN because they may be different values

**Comment by jcubic** [comment]
This doesn't answer my question, you just wrote what NaN is. Should it be `"number"` like typeof returns or should be `"nan"`? You didn't said if it's ok that it return "number" or not.
