### ISSUE TITLE
License

### ISSUE THREAD

**Issue by jcubic** [garethslinn/helprjs#2]
This is not an Open Source project if you don't add a license. By default, if something doesn't have a license, according to Copyright law everything is "All Right Reserved" by default. Writing that something is Open Source doesn't make it Open Source.

**Comment by garethslinn** [comment]
Can you point out where this clarifies your statement from the document?  Thanks :-)
https://www.npmjs.com/policies/open-source-terms

**Comment by jcubic** [comment]
To specify the license you can use package.json or add LICENSE file I suggest adding both.

**Comment by jcubic** [comment]
I suggest not closing an issue if you expect me to answer your question and/or clarify. Closing means the end of the discussion, I don't care what you have to say. At least this is how I understand it.

The standard way to define a license is the LICENSE file so it's visible what license the project has. Just click add file type LICENSE and pick the license you want. If it's ISC (default added by npm init) then just pick ISC license text and copy-paste it into the LICENSE file (I'm not sure if GitHub has a template for it).
